extender_type: "agent"
extender_file: "agent_kharon.so"
ax_file: "ax_config.axs"

agent_name: "kharon"
agent_watermark: "c17a905a"
listeners:
  - "KharonHTTP"
  - "BeaconServerless"
multi_listeners: false
