#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
AGENT_DIR="$PROJECT_DIR/agent/src_beacon"

echo "[*] Building Kharon agent..."

if ! command -v nasm > /dev/null 2>&1; then
    echo "[!] NASM not found. Install: apt install nasm"
    exit 1
fi

if ! command -v clang++ > /dev/null 2>&1; then
    echo "[!] clang++ not found. Install: apt install clang lld"
    exit 1
fi

AGENT_UUID="${KH_AGENT_UUID:-$(cat /proc/sys/kernel/random/uuid)}"
SLEEP_TIME="${KH_SLEEP_TIME:-5}"
JITTER="${KH_JITTER:-20}"
SYSCALL="${KH_SYSCALL:-0}"
AMSI_ETW="${KH_AMSI_ETW_BYPASS:-0}"
BOF_HOOK="${KH_BOF_HOOK_ENABLED:-0}"

SLEEP_MASK="${KH_SLEEP_MASK:-0}"
HEAP_MASK="${KH_HEAP_MASK:-0}"

WORKTIME_ENABLED="${KH_WORKTIME_ENABLED:-0}"
WORKTIME_START_HOUR="${KH_WORKTIME_START_HOUR:-0}"
WORKTIME_START_MIN="${KH_WORKTIME_START_MIN:-0}"
WORKTIME_END_HOUR="${KH_WORKTIME_END_HOUR:-0}"
WORKTIME_END_MIN="${KH_WORKTIME_END_MIN:-0}"

KILLDATE_ENABLED="${KH_KILLDATE_ENABLED:-0}"
KILLDATE_DAY="${KH_KILLDATE_DAY:-0}"
KILLDATE_MONTH="${KH_KILLDATE_MONTH:-0}"
KILLDATE_YEAR="${KH_KILLDATE_YEAR:-0}"

GUARDRAILS_USER="${KH_GUARDRAILS_USER:-}"
GUARDRAILS_HOST="${KH_GUARDRAILS_HOST:-}"
GUARDRAILS_IP="${KH_GUARDRAILS_IPADDRESS:-}"
GUARDRAILS_DOMAIN="${KH_GUARDRAILS_DOMAIN:-}"

SPAWNTO="${KH_SPAWNTO_X64:-C:\\\\Windows\\\\System32\\\\notepad.exe}"
FORK_PIPE="${KH_FORK_PIPENAME:-\\\\\\\\\\\\\\\\\\\\x2e\\\\pipe\\\\kharon}"
INJECTION_ID="${KH_INJECTION_ID:-0}"
INJECTION_PE="${KH_INJECTION_PE:-0}"
INJECTION_SC="${KH_INJECTION_SC:-0}"
STOMP_MODULE="${KH_STOMP_MODULE:-}"

WEB_SECURE="${WEB_SECURE_ENABLED:-TRUE}"
WEB_PROXY="${WEB_PROXY_ENABLED:-FALSE}"
WEB_PROXY_URL="${WEB_PROXY_URL:-}"
WEB_PROXY_USER="${WEB_PROXY_USERNAME:-}"
WEB_PROXY_PASS="${WEB_PROXY_PASSWORD:-}"
SMB_PIPE="${SMB_PIPE_NAME:-'L\"\"'}"

MALLEABLE_BYTES="${HTTP_MALLEABLE_BYTES:-{ 0x00 }}"

echo "    Agent UUID: $AGENT_UUID"
echo "    Sleep: ${SLEEP_TIME}s, Jitter: ${JITTER}%"
echo "    Syscall: $SYSCALL, AMSI/ETW: $AMSI_ETW"

cd "$AGENT_DIR"

make clean 2>/dev/null || true

make x64 \
    KH_AGENT_UUID="$AGENT_UUID" \
    KH_SLEEP_TIME="$SLEEP_TIME" \
    KH_JITTER="$JITTER" \
    KH_SYSCALL="$SYSCALL" \
    KH_AMSI_ETW_BYPASS="$AMSI_ETW" \
    KH_BOF_HOOK_ENABLED="$BOF_HOOK" \
    KH_SLEEP_MASK="$SLEEP_MASK" \
    KH_HEAP_MASK="$HEAP_MASK" \
    KH_WORKTIME_ENABLED="$WORKTIME_ENABLED" \
    KH_WORKTIME_START_HOUR="$WORKTIME_START_HOUR" \
    KH_WORKTIME_START_MIN="$WORKTIME_START_MIN" \
    KH_WORKTIME_END_HOUR="$WORKTIME_END_HOUR" \
    KH_WORKTIME_END_MIN="$WORKTIME_END_MIN" \
    KH_KILLDATE_ENABLED="$KILLDATE_ENABLED" \
    KH_KILLDATE_DAY="$KILLDATE_DAY" \
    KH_KILLDATE_MONTH="$KILLDATE_MONTH" \
    KH_KILLDATE_YEAR="$KILLDATE_YEAR" \
    KH_GUARDRAILS_USER="$GUARDRAILS_USER" \
    KH_GUARDRAILS_HOST="$GUARDRAILS_HOST" \
    KH_GUARDRAILS_IPADDRESS="$GUARDRAILS_IP" \
    KH_GUARDRAILS_DOMAIN="$GUARDRAILS_DOMAIN" \
    KH_SPAWNTO_X64="$SPAWNTO" \
    KH_FORK_PIPENAME="$FORK_PIPE" \
    KH_INJECTION_ID="$INJECTION_ID" \
    KH_INJECTION_PE="$INJECTION_PE" \
    KH_INJECTION_SC="$INJECTION_SC" \
    KH_STOMP_MODULE="$STOMP_MODULE" \
    HTTP_MALLEABLE_BYTES="$MALLEABLE_BYTES" \
    WEB_SECURE_ENABLED="$WEB_SECURE" \
    WEB_PROXY_ENABLED="$WEB_PROXY" \
    WEB_PROXY_URL="$WEB_PROXY_URL" \
    WEB_PROXY_USERNAME="$WEB_PROXY_USER" \
    WEB_PROXY_PASSWORD="$WEB_PROXY_PASS" \
    SMB_PIPE_NAME="$SMB_PIPE"

if [ -f "$AGENT_DIR/Bin/Kharon.x64.bin" ]; then
    SIZE=$(stat -c%s "$AGENT_DIR/Bin/Kharon.x64.bin" 2>/dev/null || stat -f%z "$AGENT_DIR/Bin/Kharon.x64.bin" 2>/dev/null)
    echo ""
    echo "[+] Agent built: $AGENT_DIR/Bin/Kharon.x64.bin ($SIZE bytes)"
    echo "    Set HTTP_MALLEABLE_BYTES to embed your Lambda profile before building."
else
    echo "[!] Build may have failed. Check output above."
fi
